[workspace]
members = ["quash"]
resolver = "3"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
bytes = "1"
getrandom = "0.4"
hex = "0.4"
quinn = "0.11"
rcgen = "0.14"
rustls = { version = "0.23", default-features = false, features = [
  "ring",
  "std",
] }
rustls-pemfile = "2"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "io-util",
  "io-std",
  "net",
  "process",
  "time",
  "signal",
  "sync",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.clippy]
all = "deny"
expect_used = "deny"
nursery = "deny"
panic = "deny"
pedantic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
future_incompatible = "deny"
unsafe_code = "deny"
unused = "deny"

[workspace.metadata.crane]
name = "quash"

[workspace.package]
edition = "2024"
version = "2026.9.18"
